name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g firebase-tools
      - run: firebase deploy --only hosting --project bliss-gems-one --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
